### ISSUE TITLE
General Characters Art Direction

### ISSUE THREAD

**Issue by NateAGeek** [NateAGeek/CopsAndRobbers-EECS-395-GameDev#20]

**Comment by NateAGeek** [comment]
I made this: 
Comments?

![Example](https://raw.githubusercontent.com/NateAGeek/CopsAndRobbers-EECS-395-GameDev/master/FunFiles/ArtDirection/HeadModel.png)

**Comment by NateAGeek** [comment]
The Head so far... Need to make more clean, but it is a start...

![untitled](https://cloud.githubusercontent.com/assets/1813055/6161928/fc3c70ca-b23e-11e4-9ce1-8e30e8e7b50f.png)

**Comment by elsyd** [comment]
That could be anything. That could literally be anything. Why are we to just accept your claim that it is a head? It could be a radish.

**Comment by NateAGeek** [comment]
No you're a radish

![](http://cloud.graphicleftovers.com/12009/1367189/cartoon-angry-radish.jpg)

**Comment by NateAGeek** [comment]
There's your fricken radish

![untitled](https://cloud.githubusercontent.com/assets/1813055/6162033/e5f697a8-b240-11e4-901a-8c694ba066e0.png)

**Comment by NateAGeek** [comment]
I have a base model, it needs to be prettify

**Comment by NateAGeek** [comment]
Also, skeleton system needs to be made for animations

**Comment by NateAGeek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1813055/6181729/1843a4fa-b2fd-11e4-8b8d-4eb2faa4344c.png)

**Comment by petehuang** [comment]
i like this a lot actually. fits very well with a cartoony theme. adorable too.

**Comment by NateAGeek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1813055/6223552/ffa3e364-b631-11e4-830e-a808cef42e60.png)

Did some Retopology. The thing just needs to be rigged up. Then, animating!

**Comment by NateAGeek** [comment]
Note to Self: Those fingers feel off...

**Comment by NateAGeek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1813055/6316522/a4c894f6-b9ee-11e4-94f0-69f7df75eb55.png)

He can now go full derp

**Comment by NateAGeek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1813055/6317479/94bc7d0c-ba1b-11e4-90bf-70a9bd5f45f3.png)

ooooooooo

**Comment by elsyd** [comment]
Looking like a true alien. Also those fingers are giving me uncanny valley effects.

**Comment by NateAGeek** [comment]
I think this is done
